#!/usr/bin/env python3
"""Consolidate r1 lens findings -> consolidated.json (Perkins round 1)."""
import json, os

R = "/Users/moses/code/_bmad-output/perkins/packet-plumber-v2-5.7-runtime-telemetry/r1"

def f(source, severity, category, title, location, evidence, detail, fix):
    return {"source": source, "severity": severity, "category": category, "title": title,
            "location": location, "evidence": evidence, "detail": detail,
            "recommended_fix": fix, "verification": "confirmed"}

EV_DROW = ("D,21,0,0,0,1  (real stream, tick 21 - the ONLY D row; the PR body adds "
           "D,21,1,1,0,1 which the stream never emits; P,21,1 shows dropped=0 "
           "contradicting the 'shed 1 (streaming)' prose)")
EV_EXIT = ("spec-5-7 line 72: 'unwritable path -> eprintln + exit 1' vs app/main.odin: "
           "'if err := os.write_entire_file(...); err != nil { fmt.eprintfln(...) }' - no exit code change")
EV_TOKEN = ('app: \'if os.args[i] == "--stats-out" && i+1 < len(os.args) { stats_path = os.args[i+1] }\' '
            '(no else-error) vs harness: \'if i+1 >= len(rest) || stats_out != "" { usage() }\'')
EV_CLASSMATH = ("stats_test.odin asserts only pipe math (cap_units==15, carried==queued*30, util formula, "
                "offered>=carried); zero assertions on class loss_pct / avg_latency_ms / accumulator mapping / sla latches")

findings = [
 f(["tests"], "blocker", "coverage-gap",
   "P0 record math unasserted: class loss_pct, avg_latency_ms, accumulator mapping and SLA-latch copy have no value-level pin",
   "core/stats_test.odin:96-116", EV_CLASSMATH,
   "C rows are half the stream artifact; byte-identity passes on identically-wrong values, and the copy is separate from sla_evaluate - a C-row formula regression ships undetected.",
   "Extend test_stats_derivation_congested: assert per class row loss_pct == dropped*100/(delivered+dropped), avg_latency_ms == total_latency_ms/delivered, the demand/delivered/dropped mapping from flow.sla, and latches == flow.sla_breach."),
 f(["tests"], "blocker", "coverage-gate",
   "Advisory test gate: FAIL (P0 ~82%, P1 ~15%, overall ~65%)",
   "N/A", "N/A",
   "P0: record math partially pinned (pipe math yes, class/D-row math no). P1: app emission loop 0%, PP_DEBUG compile gate 0%, stats-check manual-only, bundle replication 0%. Gate requires P0 100%, P1 >=80%.",
   "Pin C-row/D-row/bundle-replication values in stats_test; wire stats-check + a PP_DEBUG build into the suite/CI; factor the app emission loop into a shared pinned helper."),
 f(["edge","acceptance","security","architecture"], "warning", "boundary",
   "App silently ignores a dangling --stats-out token; the harness rejects the same input with a usage error",
   "app/main.odin:142-147", EV_TOKEN,
   "Same flag, two CLIs, inconsistent validation - the app runs with telemetry silently off on a typo'd invocation.",
   "In the app parse loop, error + exit non-zero when --stats-out has no following token, mirroring the harness."),
 f(["edge","codebase","blind"], "warning", "error-handling",
   "App stats-stream write failure prints but exits 0 - the spec I/O matrix mandates eprintln + exit 1",
   "app/main.odin:170-176", EV_EXIT,
   "Direct violation of the committed spec's app-row error contract (spec-5-7 line 72).",
   "Set a failing exit code after the eprintln in the exit defer (or surface the failure so main returns non-zero)."),
 f(["codebase","blind"], "warning", "doc-integrity",
   "PR body sample excerpt contains a D row the real stream never emits; prose contradicts the P row",
   "_pr_body.md:49-64", EV_DROW,
   "Real tick-21 stream verified: only D,21,0,0,0,1 exists; P,21,1 shows dropped=0 yet the prose says 'shed 1 (streaming)'. AC6's artifact excerpt misrepresents the stream.",
   "Replace the excerpt with the verbatim real tick-21 rows and fix the pipe-1 prose."),
 f(["codebase","blind"], "warning", "doc-integrity",
   "PR body claims a 'seed column' disambiguates appended runs; the serializer writes no seed column",
   "_pr_body.md:135 vs core/stats.odin stats_write_csv",
   "G row format: 'G,%d,%d,%016x,%d,%d' (tick,gen,sim_hash,score,meter) - no seed; the 'App restart appends' decision cites a nonexistent column.",
   "The documented append-disambiguation mechanism does not exist in the emitted format; tick-restart + sim_hash are the only separators.",
   "Either add the seed to the G row/header or fix the PR body claim (tick restart + sim_hash alone disambiguate)."),
 f(["acceptance","tests","blind"], "warning", "doc-integrity",
   "Committed spec leaves the AC5 full-suite checkbox unchecked while the PR body claims the suite green",
   "_bmad-output/implementation-artifacts/spec-5-7-runtime-telemetry.md:109",
   "Line 109: '- [ ] Full suite: odin test core + harness build + harness run all green, goldens byte-identical -- AC5.' (unchecked)",
   "Substance verified green locally by this review (162 core tests, 25/25 demos, goldens byte-identical) - the record contradicts itself; tick the box.",
   "Tick the AC5 checkbox (the suite is green at this sha)."),
 f(["edge","architecture"], "warning", "schema",
   "D rows emit per drop event, never aggregated per (pipe,class,reason); the count column is always 1 despite the legend implying aggregation",
   "core/stats.odin:205-224",
   "append(&rec.drops, Stats_Drop_Row{... count = 1}) per site; legend: '# D <tick>,<pipe>,<class>,<reason>,<count>'",
   "Schema/doc mismatch on the artifact the user will diff; heavier loads emit duplicate rows with count=1.",
   "Aggregate per (pipe,class,reason) per tick (sum into count), or document count as reserved/always-1."),
 f(["tests"], "warning", "coverage-gap",
   "D-row accounting (member replication, class/reason, E22 exclusion) and offered == carried + drops*bw never asserted",
   "core/stats_test.odin", EV_CLASSMATH,
   "The D-row semantics (replication to every live bundle member) are documented but untested anywhere automated.",
   "Add a parallel-bundle congestion test asserting replicated D rows and the offered equality."),
 f(["tests"], "warning", "coverage-gap",
   "Bundle-member replication semantics (pooled-bundle scenario) untested",
   "core/stats.odin:201", EV_CLASSMATH,
   "No test constructs a parallel-pipe bundle, so the bundle-shared load columns are never exercised.",
   "One test with a 2-member bundle asserting identical load columns + replicated D rows across members."),
 f(["tests"], "warning", "coverage-gap",
   "App-side stats emission loop has zero automated coverage; the unit mirror mirrors the harness loop, not the app's",
   "app/main.odin:234",
   "app computes stats under 'if app.stats_live || app.overlay_on' with its own event-mark/hash logic - no test executes this path.",
   "The app loop could diverge from the pinned harness path without any test failing.",
   "Extract a shared per-step stats emission proc (mark, hash, compute, append) both drivers call; pin it with a unit test."),
 f(["tests"], "warning", "coverage-gap",
   "PP_DEBUG-gated code (debug_overlay.odin, harness/overlay.odin, D toggle) has no automated compile or render gate",
   ".github/workflows/ci.yml:75",
   "CI: 'run: odin build app -out:app.bin' - no -define:PP_DEBUG=true build anywhere; overlay code can rot between reviews.",
   "Both app builds verified compiling at this sha locally; add the gate so it stays true.",
   "Add a CI step: odin build app -define:PP_DEBUG=true (and optionally the harness with the define)."),
 f(["acceptance","tests"], "note", "coverage-gap",
   "stats-check (the AC1 end-to-end replay-identity pin) is a manual verb, not wired into the harness suite or CI",
   "harness/main.odin:67-77",
   "usage lists stats-check; nothing invokes it automatically (this review ran 2 demos green by hand).",
   "The strongest pin exists but can silently stop being run.",
   "Invoke stats-check for a demo subset (e.g. pause + qos_contention) inside harness run or CI."),
 f(["security","architecture"], "note", "boundary",
   "stats_check writes predictable /tmp paths (symlink-following, collision-prone; /tmp is not portable to the Windows target)",
   "harness/stats.odin:27-28",
   'live_path := fmt.aprintf("/tmp/pp-stats-%s-live.csv", demo)',
   "Local dev tool risk + portability; demo name interpolates unvalidated into the path.",
   "Write under gitignored bin/ (like overlay-check) or use a create-temp API; reject path separators in demo names."),
 f(["security"], "note", "resource",
   "App accumulates the whole session's stream in memory, flushed only at exit (crash loses it)",
   "app/main.odin:166-176,242",
   "stats_sb grows per stepped tick on the default allocator until the exit defer writes it.",
   "Write-at-exit is a documented decision; the unbounded-growth + crash-loss angle is the new cost. Availability only - sim numbers, not secrets.",
   "Consider incremental append-per-tick (or per-N-ticks) flush if long sessions matter."),
 f(["edge"], "note", "error-handling",
   "overlay-check exits 0 with an overlay-free PNG when zero sim ticks were stepped",
   "harness/overlay.odin:79-131",
   "wall_max=0 (cap_ms=0 or fully-paused window) -> loop skipped -> stats_valid=false -> frame rendered WITHOUT overlay, PNG written, return 0.",
   "A green-looking AC3 verification artifact with no overlay in it.",
   "Fail (or warn loudly) when stats_valid is false at render time."),
 f(["codebase"], "note", "duplication",
   "Demo teardown block inlined a third time instead of a shared demo_destroy helper",
   "harness/overlay.odin:38-45",
   "defer { for n in d.nodes { delete(n.type_name) } ... } mirrors run_demo/load_demo_replay copies.",
   "Three copies of the parse-teardown will drift.",
   "Extract demo_destroy(d) next to parse_demo; use at all three sites."),
 f(["codebase"], "note", "discoverability",
   "overlay-check verb missing from the harness usage string (and its required <ms> arg undiscoverable)",
   "harness/main.odin:192",
   "usage(): 'harness run|save [demo...] [--stats-out <path>] | replay <demo> <log.bin> | drift-check | preview-check | stats-check <demo>' - no overlay-check.",
   "PP_DEBUG builds accept the verb but never advertise it.",
   "Add '| overlay-check <demo> <ms> (PP_DEBUG)' to the usage line."),
 f(["architecture","blind"], "note", "doc-accuracy",
   "overlay_on App field is not compile-gated despite comments claiming 'field + toggle are compile-excluded'",
   "app/main.odin:127",
   "overlay_on: bool declared ungated in App; the toggle handler and draw site ARE when-gated.",
   "One dead bool in release builds; comment overclaims.",
   "Wrap the field in when #config(PP_DEBUG,false) too, or fix the comment."),
 f(["architecture"], "note", "duplication",
   "overlay_check re-implements the demo stepping loop and frame composition, diverging from capture_frame/run_demo batching",
   "harness/overlay.odin:82-113",
   "Standalone wall-tick loop + separate BeginDrawing composition (draw_world/forecast/health/crisis_banner) duplicating run_demo's capture path.",
   "Drift risk between the verification render and the capture render.",
   "Share the stepping + composition helpers with run_demo's capture path where feasible."),
 f(["blind"], "note", "doc-accuracy",
   "overlay.odin header comment says the PNG lands in _bmad-output/, the code writes bin/",
   "harness/overlay.odin:1-4,129",
   'Header: writes a PNG to _bmad-output/overlay-<demo>-<ms>.png vs code: fmt.aprintf("bin/overlay-%s-%dms.png", ...).',
   "Comment points the user at the wrong directory.",
   "Fix the header comment to bin/ (gitignored, per the PR body decision)."),
 f(["blind"], "note", "doc-accuracy",
   "Spec Code Map/Tasks omit the two new harness files the diff adds (harness/stats.odin, harness/overlay.odin)",
   "_bmad-output/implementation-artifacts/spec-5-7-runtime-telemetry.md",
   "Task checkboxes list core/stats.odin, stats_test, harness/run.odin, harness/main.odin, app files - not the two new harness files (the PR body does list them).",
   "Spec record incomplete vs the shipped code.",
   "Add the two files to the spec's tasks/code map."),
 f(["tests"], "note", "coverage-gap",
   "--stats-out CLI error paths untested (duplicate flag, missing token, !=1 demo, unwritable path)",
   "harness/main.odin:117-127",
   "Parse-validation branches have no tests; only happy paths are exercised.",
   "Low-risk parse guards, but they are the flag's whole error surface.",
   "A few shell-level or unit tests over the parse function if it's extracted."),
]

out = {
  "round": 1, "job": "packet-plumber-v2-5.7-runtime-telemetry",
  "pr": "https://github.com/solarity-services/Packet-Plumber/pull/47",
  "reviewed_sha": "6b0949765340f1233e31b498bccfea73b4ca9f5e",
  "reviewers_completed": 7, "reviewers_total": 7, "failed_layers": [],
  "lens_retries": {"blind": "re-dispatched once (raw tab bytes in JSON strings); retry valid",
                   "architecture": "one continuation nudge after a 429 rate-limit stall; same brief"},
  "total_findings": 38, "confirmed": 36, "rejected": 2, "unverifiable_speculative": 0,
  "rejected_detail": [
    {"source": "blind", "title": "unused local 'g' fails to compile, contradicting 162 tests green",
     "reason": "FALSIFIED by direct run: odin test core at this sha compiles and finishes 162/162 tests, RC=0, no unused-var diagnostics."},
    {"source": "blind", "title": "util_pct divides bandwidth units by packet-count cap",
     "reason": "Premise false: bundle_cap is the STATIC SUM of tier capacity_units (bandwidth units/tick, balance.json), the same dimension as carried (queued x packet_bandwidth). Formula documented in the PR body and pinned by unit test; delegated metric definition."}
  ],
  "findings": findings,
  "counts": {"blocker": 2, "warning": 10, "note": 11},
  "reviewer_agreement": [
    "dangling --stats-out token (edge/acceptance/security/architecture)",
    "app exit-0 on write failure vs spec exit 1 (edge/codebase/blind)",
    "seed-column claim false (codebase/blind)",
    "AC5 checkbox unchecked (acceptance/tests/blind)",
    "D-row count always 1 (edge/architecture)",
    "stats-check manual-only (acceptance/tests)",
    "/tmp hardcoded paths (security/architecture)",
    "overlay_on comment mismatch (architecture/blind)"],
  "local_verification": ("odin test core 162/162 green; tools/harness.sh run 25/25 demos green, goldens "
                          "byte-identical (git clean); stats-check qos_contention 65626B + pause 555483B "
                          "live==replay byte-identical; two live runs cmp-identical; odin build app + app "
                          "-define:PP_DEBUG=true both compile; real tick-21 stream extracted and diffed "
                          "against the PR excerpt"),
  "verdict": "NEEDS CHANGES"
}

with open(os.path.join(R, "consolidated.json"), "w") as fh:
    json.dump(out, fh, indent=1)
print("written:", out["counts"], "verdict:", out["verdict"], "| findings:", len(findings))
