#!/usr/bin/env python3
# r2 consolidated.json generator (Perkins round 2 — packet-plumber-ue-slice-1)
import json

rows = [
# (sources, severity, category, title, location, evidence, detail, fix, carry-or-None)
(["codebase","perkins-mechanical"],"blocker","view-geometry",
 "Road ribbons are anchored at Center-(Width/2,Width/2) instead of Center-(Length/2,Width/2) — every road is displaced ~(Length-Width)/2 (~41 px) along its axis and the nodes sit disconnected from the roads",
 "Source/PacketPlumber/PPRunView.cpp:142,153",
 "CasingSlot->SetPosition(Center - FVector2D((Width + 4.0f) * 0.5f, (Width + 4.0f) * 0.5f)); CasingSlot->SetSize(FVector2D(Length, Width + 4.0f));  // same for Fill at :153 — X anchor uses Width/2, not Length/2",
 "Pixel-verified in ALL committed frames: white road pixels span x=258-452 while node centers sit at x=214/311/408 (predicted buggy span 253.5-447.1 vs correct 214-408) — the source node floats ~28 px left of the road start and the road overshoots ~30 px past the sink. The slice's primary deliverable (the MM look) renders broken geometry; the checklist scores axis 2 PASS on these frames. Present since 9dabfbe (r1's vision-only road check could not see it).",
 "Anchor both ribbons at Center-(Length/2,Width/2) (casing: (Length/2,(Width+4)/2)); re-capture the evidence frames; add a geometric check (road endpoints vs node centers) to the capture pipeline.",
 None),
(["codebase","perkins-mechanical"],"warning","view-geometry",
 "Packet dot renders half a tile (+12 px x/y) off the road it rides — PacketPosIn bakes +0.5 node centers, GridToScreenV adds +0.5 again",
 "Source/PacketPlumber/PPRunView.cpp:276 + 406-409",
 "From = FVector2D(Node.Pos.X + 0.5f, Node.Pos.Y + 0.5f); ... return FMath::Lerp(From, To, ...);  // then GridToScreenV: Offset + (GridPos + 0.5f) * kTilePx * Scale",
 "Committed frames: dot at y=70-75 vs road band 52-70 (centerline 61) — the dot hangs below the road's bottom edge, not 'mid-road' as the PR body and checklist claim. The dot EXISTS and moves (r1 fabrication fixed) but is mis-placed.",
 "Return raw node grid positions from PacketPosIn (let GridToScreenV add the single +0.5), or subtract it at the call site; re-verify the dot rides the road centerline.",
 None),
(["blind","edge","acceptance","architecture","codebase"],"warning","determinism-spine",
 "A bare same-tick re-step is still state-mutating: demand is never consumed (double-spawn), the nonce redraws (RNG advances), the serve pass double-serves",
 "Source/PacketPlumberCore/Public/PacketPlumberCore/PP_Sim.h:73-79,121 + PP_Flow.h:127-131",
 "if (Tick == State.Tick && NumCommands > 0) { latch; return; }  // bare re-step falls through — FlowStep spawns Req.Tick==Tick again (F.Demand never erased) + State.TickNonce = RngNext(State.Rng) unconditionally",
 "The r1 same-tick warning is only half-closed: the command case latches, but the documented 'bare re-step stays legal' path silently diverges sim state if any future caller re-steps. No in-repo runtime caller does (drivers step forward; only tests re-step).",
 "Either make the bare re-step a true no-op (return early when Tick == State.Tick) or consume demand entries on spawn; keep one test pinning whichever contract you choose.",
 "still present since round 1 (partially addressed)"),
(["edge","acceptance","architecture","blind","perkins"],"warning","input",
 "E4 snap radius is a world-px canon constant compared unscaled in screen px — the effective radius varies with window size/DPI",
 "Source/PacketPlumber/PPCommandBus.cpp:32,47",
 "const float RadiusPx = static_cast<float>(PP::kSnapRadius);  // kSnapRadius = 36 'world px, inclusive (E4)' (PP_Balance.h:49) ... if (D2 <= RadiusPx * RadiusPx && D2 < BestD2)  // D2 in screen px (node positions via MakeScreenFit)",
 "At the capture DPI (widget 1896x1081, Scale 1.386) the effective world-px radius is ~26; at the 1280x720 design ref (Scale 0.923) it is ~39. The E4 canon ('world px, inclusive — the hard correctness bound') is viewport-dependent in the input layer. No sim-state impact (node ids are logged).",
 "Compare in world px (divide the screen delta by Fit.Scale) or scale the radius by Fit.Scale before the compare; pin the boundary case in a test.",
 None),
(["blind","acceptance","edge","architecture","tests"],"warning","view-truth",
 "'appears THIS frame' is inert: EndDraw's immediate BuildSnapshot updates the GameMode snapshot at the SAME tick, but the view only re-reads when Tick changes — the drawn pipe still waits for the next 20 Hz step",
 "Source/PacketPlumber/PPRunGameMode.cpp:196-202 + Source/PacketPlumber/PPRunView.cpp:338",
 "// immediate refresh so the drawn pipe appears THIS frame ... BuildSnapshot();  // then NativeTick: const PPView::FSnapshot &Next = GameMode->GetSnapshot(); if (Next.Tick != CurSnapshot.Tick) { ... }",
 "The r2 'fix' for r1 note 33 is a no-op: change detection is Tick-keyed, so a same-tick snapshot update is invisible to the widget; the new comment claims THIS frame. Delay is <=50 ms (cosmetic) but the claim and the code disagree.",
 "Key the view's rebuild on TopologyGen (already in the snapshot) or force a view refresh from EndDraw; or fix the comment to '<=50 ms (next tick)'.",
 "still present since round 1 (attempted fix is inert)"),
(["architecture"],"warning","hang",
 "FPPSimDriver::Advance infinite-loops once the run is terminal: Step returns without advancing Tick, so while (State.Tick < TargetTick) never exits",
 "Source/PacketPlumber/Public/PPSimDriver.h:38-42 + PP_Sim.h:63-67",
 "while (State.Tick < TargetTick) { PP::Step(State, State.Tick + 1); ++Stepped; }  // Step: if (State.bTerminal) { return; } — Tick never moves",
 "Guaranteed game-thread hang the moment story 1.4 wires a win/lose transition (tests already set bTerminal). Unreachable in slice-1 live paths — latent, but the driver is shipped API.",
 "Break the loop when Stepped exceeds a bound or Step reports no advance (return a bool / check State.Tick moved); add a terminal-state driver test.",
 None),
(["blind","edge","acceptance","architecture","codebase","tests"],"warning","golden-integrity",
 "flow_summary.spawned is computed by two different formulas on the two golden writers (standalone: live+delivered; engine PPProbe: total Demand.size()) — they agree only at the canonical 100-tick point",
 "tests/spine_check.cpp:641 vs Source/PacketPlumberEditor/PPProbeCommandlet.cpp:137",
 "spine_check: static_cast<int>(State.Flow.Packets.size()) + State.Score, // spawned = delivered + live   |   PPProbe: static_cast<int32>(State.Flow.Demand.size()), State.Score, ...",
 "Demand is seeded T=5..95 step 10 + 98 (11 entries) regardless of the -ticks param; at ticks<98 PPProbe reports 11 while realized spawns are fewer — the two surfaces diverge on any non-canonical run, and SCHEMA.md claims the three writers are single-sourced. Diagnostics-only (not the state hash).",
 "Derive spawned identically on both surfaces (live+delivered, or emit Demand.size() on both + rename the key); extend compare-golden to a second tick count to pin it.",
 None),
(["acceptance","perkins"],"warning","config",
 "FixedFrameRate=20 pins the render clock to the sim rate — the inter-snapshot (20 Hz -> 60 fps) easing half is structurally unreachable in the shipped config",
 "Config/DefaultEngine.ini:9-10 + Source/PacketPlumber/PPRunView.cpp:338-360",
 "bUseFixedFrameRate=True / FixedFrameRate=20.000000  // NativeTick runs ~20 fps == sim rate so ElapsedSinceSnapshot is always ~full tick and the eased inter-snapshot lerp never renders an intermediate frame",
 "The PR/checklist claim 'cubic ease-in-out across BOTH the inter-snapshot fraction (20 Hz sim to 60 fps view) and the edge progress' — the first half is dead code under the pinned config. The visible motion (per-tick EaseInOut over edge progress) is real; the mechanism claim is overstated.",
 "Either unpin the render frame rate (the sim stays 20 Hz via the driver — ODN-2 does not require capping the render clock) or reword the claim; decide before slice 2 builds on the easing.",
 None),
(["codebase","perkins-mechanical"],"warning","evidence-integrity",
 "slice1-2-drawn-pipe.png is a pre-fix build frame (roads rendered OVER nodes) committed as the current axis-2/3 evidence",
 "docs/goldens/screens/slice1-2-drawn-pipe.png + docs/goldens/look-parity-checklist.md:11",
 "Pixel scan: sink node shows 141 visible px in slice1-2 vs 401 in the r2-rebuilt slice1-3 (roads-over-nodes covers the disc); the r2 code renders roads UNDER nodes (RefreshPipes before RefreshNodes)",
 "The committed static-look evidence frame contradicts the committed code's z-order — it was not re-captured after the r2 view fixes.",
 "Re-capture slice1-2 from the current build (after fixing the road anchor) so the checklist cites frames the committed code actually produces.",
 None),
(["tests"],"warning","coverage-gap",
 "UPPRunView (430 lines) has zero automation coverage and the snap's boundary/miss paths plus the real Enhanced-Input handler path are untested",
 "Source/PacketPlumber/PPRunView.cpp + Source/PacketPlumberCoreTests/PPInputTests.cpp:90",
 "The headless input test binds FireDrawStartForTest on its OWN UEnhancedInputComponent and drives GM->BeginDraw with hardcoded design-ref coords — the controller's SetupInputComponent, GetViewportSize branch, and every view-layer geometry function are unexercised",
 "Three view regressions shipped in r2 alone (invisible dot, pool wipe, road anchor) — the surface with the worst track record has no automated net. Advisory gate: CONCERNS.",
 "Add automation for MakeRoad/MakePacketDot geometry (slot math vs expected fit), SnapToNode boundary/miss (pure math — testable headless), and drive the controller's own SetupInputComponent in the test.",
 None),
(["security"],"warning","attack-surface",
 "Committed .uproject enables UE_MCP_Bridge: an unauthenticated loopback WebSocket (execute_python) auto-starts on every editor boot",
 "PacketPlumberUE.uproject + Plugins/UE_MCP_Bridge/UE_MCP_Bridge.uplugin",
 "EnabledByDefault: true in the vendored .uplugin; the uproject enable list includes UE_MCP_Bridge",
 "Upstream design; UE-MCP usage is user-approved (standing ruling) — recorded as accepted-risk posture, not a demand to change. Unchanged since r1.",
 "If the risk posture ever changes: gate the plugin to a developer config rather than the committed uproject.",
 "still present since round 1 (accepted-risk posture)"),
(["edge","tests"],"note","test-quality",
 "EcmpHash 'pinned values' CHECK is a tautology (x == x) — it can never fail and pins nothing",
 "tests/spine_check.cpp:269-270",
 'CHECK(PP::EcmpHash(0, 2, 0, 1) == PP::EcmpHash(0, 2, 0, 1), "ecmp hash must be a pure function");  // comment says \'pinned values\'',
 "A real pin compares against literal constants; this check is decorative and its comment is false.",
 "Pin the expected u64 literals (compute once, commit the constants).",
 None),
(["tests"],"note","coverage-gap",
 "UE-side automation suite omits the r1-driven regression tests (serve contention, failed-replay latch, same-tick latch) that spine-check gained",
 "Source/PacketPlumberCoreTests/PP_Slice1SimTests.cpp vs tests/spine_check.cpp:419,517",
 "PP_Slice1SimTests adds ApplyEditLiveFastPath/E29Recovery/MixedTierSteering only; contention/latch tests exist solely in the standalone runner",
 "The PR claims the suites mirror; the mirror is partial. Standalone covers the contracts, so dual-runner integrity holds.",
 "Mirror the three tests (or drop the 'mirrored' wording).",
 None),
(["edge"],"note","api-hazard",
 "EqualCostHops stale-table guard detects node-count staleness only — same-count content staleness still misroutes (no in-repo caller; Step rebuilds on Gen)",
 "Source/PacketPlumberCore/Public/PacketPlumberCore/PP_Routing.h:269-275",
 "if (Fs >= R.N || Ds >= R.N) { return false; }  // shape-vs-shape only; R.N matches a same-size different topology",
 "Latent API hazard; the r1 OOB warning is closed.",
 "Document the precondition (table built for THIS topology) or carry a table Gen.",
 None),
(["architecture"],"note","api-hazard",
 "ApplyEdit + StepScenario mixing double-applies a logged draw as a second parallel pipe, silently (no duplicate-pair rejection, no latch)",
 "Source/PacketPlumberCore/Public/PacketPlumberCore/PP_Sim.h:41 + PP_Topology.h:245",
 "ApplyDraw pushes a new pipe unconditionally after ValidateDraw (no existing-pair check); StepScenario re-applies log entries — a caller using both applies the same draw twice as bundle members",
 "No in-repo caller mixes (live driver: Step-no-commands; replay: StepScenario from fresh) — latent footgun.",
 "Document the mode split, or reject exact-duplicate logged draws on replay.",
 None),
(["edge"],"note","design-doc",
 "StateHash between a live ApplyEdit and the step boundary is intentionally not a function of (seed, log, tick) — replay converges only AT the boundary",
 "Source/PacketPlumberCore/Public/PacketPlumberCore/PP_Sim.h:42-48",
 "ApplyEdit mutates the topology immediately + logs apply_tick=next; replay re-applies at that tick (ODN-2 fast-path)",
 "Design-documented and boundary-pinned by the new convergence test; worth one doc line so future readers do not 'fix' it.",
 "Add a sentence to PP_Sim.h's header stating the in-between divergence is by design.",
 None),
(["security"],"note","future-proofing",
 "PipeTier (u16 on the v2 wire) indexes fixed-size tier arrays with no local bounds check; the future deserializer must re-validate",
 "Source/PacketPlumberCore/Public/PacketPlumberCore/PP_Routing.h:168 + PP_Bundles.h:103",
 "kTierCost[T.PipeTier[Pi]] with kTierCost[3]; ValidateDraw rejects Tier >= TIER_COUNT at every writer today",
 "Unreachable until a loader exists.",
 "Re-validate tier on load; optionally clamp/checked-index at the rebuild sites.",
 None),
(["blind"],"note","ue-pattern",
 "Input assets are NewObject'd in the PlayerController constructor (CDO construction path) — works today, engine-version-fragile pattern",
 "Source/PacketPlumber/PPRunPlayerController.cpp:22-33",
 'DrawMappingContext = NewObject<UInputMappingContext>(this, TEXT("PP_DrawContext")); // in the ctor',
 "Plain UObjects with outer=this are safe at construction; the pattern is widely used but not the documented constructor-time subobject path.",
 "Acceptable; revisit if the engine version changes (5.9 re-verify).",
 None),
(["blind","architecture"],"note","dead-code",
 "DragStartGrid stored and EndGrid computed but never read (the snap went screen-space)",
 "Source/PacketPlumber/PPRunGameMode.cpp:154,172,194",
 "DragStartGrid = MakeScreenFit(ViewportSize).ScreenToGrid(ScreenPos); ... const PP::FIntPoint EndGrid = MakeScreenFit(ViewportSize).ScreenToGrid(ScreenPos);  // EndGrid unused below",
 "Leftover from the r1 grid-space snap.",
 "Delete the dead fields/computations (or keep the grid for telemetry and say so).",
 None),
(["blind","edge","acceptance","tests"],"note","ux",
 "bHasLastEditError is write-only; the header promises status-line rejection feedback that does not exist",
 "Source/PacketPlumber/Public/PPRunGameMode.h:103 + PPRunView.cpp:426-427",
 "LastEditError = Result.Error; bHasLastEditError = true;  // StatusText->SetText(... tick/packets/score/20 Hz ...) — no error surface",
 "r1 note 29 carries; the r2 test reads the error via GetLastEditErrorForTest only.",
 "Surface the last edit error in the status line (one line of view code) or fix the header comment.",
 "still present since round 1"),
(["blind"],"note","doc-drift",
 "Spine header comments defer implemented features to future stories ('ECMP is 2.2; bundles 2.1')",
 "Source/PacketPlumberCore/Public/PacketPlumberCore/PP_Flow.h:7 + PP_Routing.h:46-48 + PP_Bundles.h:1-6",
 "// form: no BFS route cache, no LB, ever (ECMP is 2.2; bundles 2.1; QoS 3.x)",
 "This diff implements, wires, and tests ECMP + bundles; the headers read as if they are absent.",
 "Update the header comments to the landed state.",
 None),
(["blind"],"note","doc-drift",
 "PP_Balance.h claims 'the balance.json keys slice 1 reads' but 4 of its constants are unreferenced (kDemandIntervalTicks, kSurgeWarnTicks, kNetworkHealthOk, kRouterCost)",
 "Source/PacketPlumberCore/Public/PacketPlumberCore/PP_Balance.h",
 "grep: 0 refs outside PP_Balance.h for each of the four",
 "Data-as-documentation is fine; the claim overstates.",
 "Soften the header claim or mark the future-slice keys.",
 None),
(["edge"],"note","input",
 "Mid-drag viewport resize: the drag-start screen point is captured under the old fit but snapped with EndDraw's refreshed fit",
 "Source/PacketPlumber/PPRunGameMode.cpp:178-186",
 "BeginDraw stores DragStartScreen + refreshes ViewportSize; EndDraw refreshes ViewportSize AGAIN, then snaps both DragStartScreen and ScreenPos under the new fit",
 "A window resize between press and release mis-snaps the start point. Edge case; the sim rejects bad draws safely.",
 "Re-fit the start point from its stored grid, or freeze ViewportSize for the drag's duration.",
 None),
(["blind"],"note","doc-drift",
 "Shadow alpha disagrees across the codebase: header says 12%, code uses 0.14, checklist says 14%",
 "Source/PacketPlumber/Public/PPRunView.h:19 vs PPRunView.cpp:30 vs docs/goldens/look-parity-checklist.md",
 "PPRunView.h: 'Shadow black @ 12% alpha, soft blob' | kShadowTint(0.0f, 0.0f, 0.0f, 0.14f)",
 "r1 note 31 half-fixed (checklist updated; header not).",
 "Align the header comment to 14%.",
 None),
(["blind"],"note","contract-nuance",
 "Backward-tick latch writes ReplayError through the E17 terminal freeze (backward check runs before the terminal check)",
 "Source/PacketPlumberCore/Public/PacketPlumberCore/PP_Sim.h:57-67",
 "if (Tick < State.Tick) { State.ReplayError = true; return; } if (State.bTerminal) { return; }",
 "A post-terminal backward tick mutates the 'frozen' state's latch. Arguably correct (critical-divergence signal) — document the intent either way.",
 "Swap the checks or document that the divergence latch outranks the freeze.",
 None),
(["perkins"],"note","carry-forward-set",
 "r1 notes still open (unchanged by the delta): no deserializer/round-trip for v2 (#20); std::fill without <algorithm> (#22); UnknownTier / degenerate-spawn / BundleTier branches untested (#23-25); U-E2 guard cannot see the gitignored DefaultInput.ini it names (#27); GetCommandBus/bOnEdge/GetAccumulatedSeconds unused (#30); PPProbe hardcodes save_magic/save_version literals (#35); routing dump mixes slot and id label spaces (#36); GetMousePosition return ignored (#37); FlowSeedDemand unvalidated node ids (#38); BlueprintCallable NaN narrowing (#39); serve-pass comment still says 'Windows repeat' (#19 — the sibling comment was fixed, this one remains at PP_Flow.h:197-199)",
 "various",
 "Verified by grep/read at the reviewed sha; none block the slice.",
 "Carried (non-blocking hygiene set from r1).",
 "Fold into the next slice's hygiene pass.",
 None),
(["perkins"],"note","evidence-wording",
 "Evidence wording overclaims: '4 distinct positions x=223/272/320-326/369-375 across 12 frames' — the committed surface holds 2 distinct positions (272-277, 369-375); '32 px' counts 24 strict blue-dominant px (AA edges account for the rest); 'mid-road' is pixel-false at y=70-75 vs band 52-70",
 "docs/goldens/look-parity-checklist.md:22-27 + PR body",
 "checklist EVIDENCE row cites all four x positions; only three PNGs are committed (two distinct dot positions)",
 "The re-capture is honest in substance (dots real, moving, eased); tighten the wording to what is committed.",
 "Commit the other two frames or narrow the claim to the committed pairs.",
 None),
]

findings = []
for sources, sev, cat, title, loc, ev, det, fix, carry in rows:
    d = {"source": sources, "severity": sev, "category": cat, "title": title,
         "location": loc, "evidence": ev, "detail": det, "recommended_fix": fix,
         "verification": "confirmed"}
    if carry:
        d["carry"] = carry
    findings.append(d)

consolidated = {
 "job": "packet-plumber-ue-slice-1",
 "round": 2,
 "pr": 3,
 "reviewed_sha": "0256d8aad43d3029ac88538c1e67c577660d84ae",
 "reviewers_completed": 14,
 "reviewers_total": 14,
 "failed_layers": [],
 "chunking": "canonical diff 86,996 lines (merge-base 978ee8d -> 0256d8a; gh pr diff capped by the 20k-line API limit, so the canonical bytes are the worktree three-dot diff — method byte-verified against r1's canonical diff): chunk-core 3,234 x7 lenses; chunk-view 1,843 x7 lenses; Plugins/UE_MCP_Bridge 81,919 NOT lens-waved — zero r2 delta in Plugins (r1's byte-identical-to-upstream ue-mcp@1.2.4 verdict carries mechanically)",
 "raw_findings": 57,
 "rejected": 6,
 "rejected_detail": [
  {"source":"blind","title":"E29 drop-back fires on representative-pipe death even when the bundle still has live members","reason":"canon-specified E29 behavior (a packet whose pipe vanished drops back and re-forwards next tick via live members); blind lacked the spec"},
  {"source":"blind","title":"SCHEMA.md cited but absent from this diff","reason":"chunk artifact — file exists at the sha (core/view split); 3-way golden gate green first-hand"},
  {"source":"blind","title":"--probe-negative greps a relative log path while abslog writes an absolute one","reason":"script cds to ROOT; the negative-args leg passed first-hand in this round's gate-6 run"},
  {"source":"blind","title":".uproject enables UE_MCP_Bridge but no Plugins/ files in the diff","reason":"chunk artifact (plugin chunk) + r1 provenance verdict carries (zero r2 delta in Plugins/)"},
  {"source":"blind","title":"SCHEMA.md three-writer mirroring updated only on the probe writer","reason":"chunk artifact — all three writers updated within the canonical diff (spine_check + PPProbe + compare-golden); 3-way compare green first-hand"},
  {"source":"codebase","title":"the cited step_once convention does not exist","reason":"the bare re-step convention exists (spine_check StepGuards: Step(U,1); Step(U,1)) — the sub-claim is false; the mutation fact was kept via other lenses"}
 ],
 "counts": {"blocker": 1, "warning": 10, "note": 16},
 "mechanical_verification": {
  "fast_gates": "3/3 PASS first-hand (spine-check 111 checks — up from 91; the 20 new checks are the r1-warning regression pins)",
  "full_gates": "7/7 PASS first-hand (no-op rebuild, 19/19 automation incl. the two new PacketPlumber.Input.* tests, PPProbe + negative-args, 3-way golden + corrupted-golden self-test)",
  "golden_discipline": "HELD — state_hash 5e440f9c5a28892a and tick_nonce 2381141952 unchanged from r1; committed == standalone == engine at this sha; no re-bless in the r2 delta",
  "spine_untouched": "zero sim-state semantics changed by the fix commit (StateHash growth + StepScenario vector + stale-guard + same-tick latch are spine-adjacent hardening, all tested; replay-equality re-pinned)",
  "blocker1_fix": "REAL — UInputAction/UInputMappingContext created in the constructor (CDO carries them); 19/19 automation first-hand: AssetsExistAtBind + TriggerSynthesized bind, Execute the delegate, and drive a full drag -> 1 pipe + 1 log entry in the sim. Residual: the test binds on its own EIC rather than invoking the controller's SetupInputComponent (engine-orchestrated; acceptable headless)",
  "blocker2_fix": "HONEST IN SUBSTANCE — the dot exists and moves: committed frames contain 24-30 dot px at (272-277,70-75) and (370-375,70-75), the rendered color (134,183,216) is exactly the sRGB encoding of the linear constant; easing is real (per-packet prev/cur positions). Residual geometry defects filed as findings (roads +41px off-node [blocker], dot +12px off-road [warning]); vision deferred per the non-k3 VISION CAVEAT (mechanical only)",
  "routing_dump": "consistent (6 pairs / hops via node ids / topo_gen 5)",
  "plugin_provenance": "r1 verdict carries — zero r2 delta under Plugins/"
 },
 "fix_audit": {
  "blockers": "2/2 addressed: input-binds blocker fixed for real (verified first-hand); evidence-fabrication blocker fixed in substance (dots exist + move; new geometry defects found in the same frames — filed as NEW findings)",
  "warnings": "13/16 properly fixed (StateHash grow, StepScenario dynamic, EqualCostHops OOB, ApplyEdit coverage+convergence, tier steering, failed-replay latch, E29 recovery, serve contention, road pivot, shared SpawnFixture, PP_SimState include, spine-check computed summaries, camera-fit math single-sourced); 2 partially fixed with real residuals (same-tick re-step, snap screen-space); 1 carried (MCP bridge accepted-risk)",
  "notes": "fixed: #18 #26 #31(checklist side) #32 #34; carried: #19(partially) #20 #22 #23 #24 #25 #27 #28 #29 #30 #33(upgraded to warning — the fix is inert) #35 #36 #37 #38 #39"
 },
 "verdict": "NEEDS CHANGES",
 "findings": findings
}

counts = {"blocker": 0, "warning": 0, "note": 0}
for f in findings:
    counts[f["severity"]] += 1
assert counts == consolidated["counts"], (counts, consolidated["counts"])
out = "/Users/moses/code/_bmad-output/perkins/packet-plumber-ue-slice-1/r2/consolidated.json"
json.dump(consolidated, open(out, "w"), indent=1)
print("consolidated.json OK:", counts, "| raw", consolidated["raw_findings"], "| rejected", consolidated["rejected"])
