#!/usr/bin/env python3
"""Write consolidated.json for packet-plumber-v2-3.2-lane-qos r1 (post-verification)."""
import json

OUT = "/Users/moses/code/_bmad-output/perkins/packet-plumber-v2-3.2-lane-qos/r1"

def f(sources, severity, category, title, location, evidence, detail, fix, verification):
    return {"sources": sources, "severity": severity, "category": category, "title": title,
            "location": location, "evidence": evidence, "detail": detail,
            "recommended_fix": fix, "verification": verification}

findings = [
    # ---- warnings ----
    f(["architecture", "blind", "codebase", "edge"], "warning", "ui-feedback",
      "QoS rejection toast is gated on pipe selection, but the right-click dial path never selects — a rejected dial move on an unselected pipe is silent, contradicting the code's own 'never silent' intent",
      "app/main.odin:453-496 (toast in the sel_pipe block) / app/main.odin:198-209 (right-click never selects) / app/main.odin:388-393 (rejection recorded)",
      "app/main.odin:207-211: `if rl.IsMouseButtonPressed(.RIGHT) { app.drag.active = false; app.drag_to = 0; if pid, ok := pipe_hit(app, wx, wy); ok { cycle_emphasis(app, pid) } return }` — no app.sel_pipe assignment. app/main.odin:494-496: `if app.last_reject != .None && app.tick - app.reject_tick < 30 { draw_text(app, reject_label(app.last_reject), ...) }` — nested inside `if app.sel_pipe >= 0 {` (block opens :453, closes :497).",
      "cycle_emphasis's rejection branch sets last_reject, but the toast renders only inside the sel_pipe block and right-click never sets sel_pipe. An E6-rejected dial move (once never-drop content exists) is silent — the code comment at :493 claims 'a rejected dial/lane edit is never silent'. 4-lens agreement.",
      "Draw the rejection toast outside the sel_pipe gate (or have the right-click path select the hit pipe before cycling).",
      "confirmed"),
    f(["tests"], "warning", "coverage-gap",
      "App emphasis-dial interaction logic (pipe_hit, dial wrap, lane keys, toast) has zero automated coverage",
      "app/main.odin:316 (pipe_hit), :368 (cycle_emphasis), :400 (set_lane_key), :453-497 (readout/toast)",
      "app/main.odin:316: `pipe_hit :: proc(app: ^App, wx, wy: f32) -> (u32, bool) {`; :374: `next := u16((idx + 1) % i32(len(cat.balance.lane_presets)))`; :400: `set_lane_key :: proc(app: ^App, lane: u8) {`. No app-layer test exists anywhere in the repo (grep: app/ has zero @(test) files; the harness exercises core + render only).",
      "The story's launchable increment ('run the app -> set a pipe's emphasis') is the dial + keys + readout; the dial wrap math and point-to-segment hit-test are real logic with no coverage at any level. The core invariants ARE pinned — this is the app glue layer.",
      "A thin app-logic test (pure-proc extraction of cycle_emphasis's next-preset math + pipe_hit geometry) or a harness-driven input-level demo; accept a note-level gap if the team keeps app untested by design.",
      "confirmed"),
    # ---- notes ----
    f(["blind", "codebase"], "note", "memory-leak",
      "b.lane_presets leaks on every balance.json fail-fast rejection (make before any reject return; cat.balance assigned only on success)",
      "core/catalog.odin:480-549",
      "core/catalog.odin:480: `b.lane_presets = make([dynamic]Lane_Preset, 0, 4, allocator)`; :488: `if lp.id == \"\" { return {\"balance.json\", \"lane_presets\", \"preset id empty\"} }`; :549: `cat.balance = b` (last line of the balance block — every reject row returns before it).",
      "11 new reject paths return with the dynamic (+ cloned id/display strings) unfreed; catalogs_destroy's `delete(cat.balance.lane_presets)` never sees it because cat.balance was never assigned. Error-path-only (a failed catalog load aborts startup), same class as the loader's pre-existing error-path leaks.",
      "Free b.lane_presets before each reject return (or defer a cleanup flag until cat.balance is assigned).",
      "confirmed"),
    f(["edge", "security"], "note", "validation-gap",
      "No preset-count bound before u16 narrowing: >65535 lane_presets silently wraps default_preset_idx / preset_index",
      "core/catalog.odin:540, :626-631",
      "core/catalog.odin:540: `b.default_preset_idx = u16(i)`; :626-631: `preset_index :: proc(cat: ^Catalogs, id: string) -> (u16, bool) { for lp, i in cat.balance.lane_presets { if lp.id == id { return u16(i), true } } ... }` — the loader bounds preset VALUES (0..MAX_WEIGHT) but never the row COUNT against the u16 index domain.",
      "Past 65535 presets the default preset (E5 fallback + the dial's resting position + the sparse-serialization def_w baseline) silently resolves to the wrong row. Absurd catalog size, but the loader's own strictness (duplicate ids AND duplicate weight sets rejected) makes the missing count bound an inconsistency in the new validation surface.",
      "Reject `len(lane_presets) > u16::MAX` with a named Catalog_Error at load.",
      "confirmed"),
    f(["acceptance", "edge"], "note", "validation-gap",
      "default_lane_preset absent or non-string is silently tolerated (falls back to preset 0), not rejected at load",
      "core/catalog.odin:534-549, :644-647",
      "core/catalog.odin:534-536: `b.default_preset_idx = 0; dp := jstr(obj, \"default_lane_preset\"); if dp != \"\" { ... }`; :644-647: `jstr :: proc(o: json.Object, key: string) -> string { if v, ok := o[key].(json.String); ok { return v } return \"\" }`.",
      "An absent field or a type-typo (e.g. `\"default_lane_preset\": 5`) silently selects row 0, while an unknown-string value IS rejected ('not found'). The spec's I/O matrix lists 'missing default | rejected at load'; the loader's own strict-typing elsewhere makes this fallback inconsistent.",
      "Reject an absent/non-string default_lane_preset (require the field, json.String, resolvable id) per the spec's fail-fast row.",
      "confirmed"),
    f(["security"], "note", "input-validation",
      "New emphasis/lane demo directives truncate pipe ids u64->u32 with no range check — an id >= 2^32 silently targets a different (possibly live) pipe",
      "harness/demo.odin:258-277",
      "harness/demo.odin:263-267: `fid, okid := strconv.parse_uint(fields[3], 10); ... append(&d.emphasis, Emphasis_Intent{at_ms = ms, pipe = u32(fid), preset = fields[4]})` — parse_uint returns u64; u32(fid) truncates mod 2^32.",
      "A mistyped id like 4294967297 becomes pipe 1 and edits a live pipe silently — the bus's .Missing_Pipe rejection (the spec I/O matrix's promised guard) only catches non-live ids. Demo-authoring input (trusted repo files), hence note.",
      "Range-check fid <= u32::MAX before the cast and fail loudly on overflow.",
      "confirmed"),
    f(["blind", "codebase", "security"], "note", "harness-duplication",
      "intent_apply_tick_raw is a third copy of the floor(at_ms*hz/1000)+1 apply-tick formula (and shares its unbounded multiply)",
      "harness/run.odin:85-87 vs harness/demo.odin:341-343, :355-357",
      "harness/run.odin:85-87: `intent_apply_tick_raw :: proc(at_ms: i64, logic_hz: i32) -> u64 { return u64(max(0, at_ms * i64(logic_hz) / 1000)) + 1 }`; harness/demo.odin:341-343: `intent_apply_tick :: proc(d: ^Draw_Intent, logic_hz: i32) -> u64 { return u64(max(0, i64(d.at_ms) * i64(logic_hz) / 1000)) + 1 }`; :355-357 demolish_apply_tick identical.",
      "The same edit-fast-path convention now lives at three sites; a future timing-convention change must be made three times. The new proc also replicates the pre-existing unbounded at_ms*logic_hz multiply (an absurd at_ms overflows i64, wraps, and fires the command at tick 1).",
      "Have emphasis/lane lowering reuse intent_apply_tick (or a single shared helper) and bound at_ms.",
      "confirmed"),
    f(["tests"], "note", "coverage-gap",
      "Harness emphasis/lane directive error paths (parse + lowering) are untested — happy-path only",
      "harness/demo.odin:258-282, harness/run.odin:57-76",
      "harness/run.odin:57: `return fmt.tprintf(\"demo %s: unknown lane preset %q\", demo.name, d.preset)`; :68: `return fmt.tprintf(\"demo %s: unknown class %q\", demo.name, d.class)`; harness/demo.odin:261: `return {}, fmt.tprintf(\"bad emphasis at-line (want: at <n>ms emphasis <pipe> <preset>): %s\", line)`.",
      "All the new directive error branches fail loudly in code but nothing exercises them — every shipped demo uses valid directives only. The harness has zero @(test) functions by structure (its gate is the golden suite); the fail-loud guarantees are unpinned.",
      "Add negative directive rows to a harness-level check (malformed at-lines, unknown preset/class/lane) or accept the gap by design.",
      "confirmed"),
    f(["tests"], "note", "coverage-gate",
      "Advisory test gate: PASS",
      "N/A",
      "N/A",
      "P0 100% (E5/E6 floor+rejection/E8 pins, weight-only, E10 replay byte-identity + drift suite, sparse-serialization pin, lane_presets fail-fast 11/12 negative rows, qos_emphasis golden T1/T2/replay); P1 100%; overall ~85% — the only shortfalls are the app dial glue + harness directive error paths (P3/P2, no test infrastructure at those layers by design).",
      "Close the app-dial + directive-error coverage if the team wants overall >=90%.",
      "confirmed"),
    f(["acceptance"], "note", "readout-accuracy",
      "Lane-proportions readout can display percentages that don't sum to 100 (default balanced = 33/33/33 = 99%)",
      "app/main.odin:514 (percent proc; readout at 471-474)",
      "percent :: proc(cap: u32, caps: [3]u32) -> i32 { total := u64(caps[0]) + u64(caps[1]) + u64(caps[2]); if total == 0 { return 0 }; return i32((u64(cap) * 100 + total/2) / total) }",
      "Independent per-lane rounding: balanced {1,1,1} on a standard pipe (cap 15) allocates {5,5,5} -> 33/33/33 = 99% — the first readout the player sees. Cosmetic (display only), but the readout is the story's visible deliverable.",
      "Round the largest remainder up (or display one decimal), or show the raw caps when the sum is small.",
      "confirmed"),
    f(["architecture"], "note", "odn-5-data-driven",
      "pipe_hit radius hardcoded at 10 world px while the sibling interaction radius (snap_radius) is data-driven in balance.json",
      "app/main.odin:319",
      "app/main.odin:319: `radius := f32(10) // world px — comfortably inside the fat-pipe read` vs snap_node (:286): `radius := f32(app.cat.balance.snap_radius)`; balance.json carries `\"snap_radius\": 36`.",
      "The established pattern for world-px interaction radii is balance.json; the new pipe hit radius is a magic literal, so tuning it means an edit + recompile instead of a data change (ODN-5 spirit).",
      "Move the pipe-hit radius into balance.json (or derive it from snap_radius).",
      "confirmed"),
    f(["blind"], "note", "render-consistency",
      "Lane-stripe render consumes flow.lane_caps, which is one tick stale after a fast-path edit — stripes and the HUD readout can disagree transiently",
      "app/render/view.odin (draw_bundles lane-segment block) + app/main.odin:464-469 (readout freshness comment)",
      "view.odin: `if int(ps) < len(flow.lane_caps) { c := flow.lane_caps[ps]; caps_sum[0] += c[0]; ... }`; main.odin:466-468: `// (NOT flow.lane_caps: a fast-path edit this frame has not been stepped yet, so the flow buffer would be one frame stale; the pure proc is the same allocation the flow rebuilds, floor + all).`",
      "A right-click dial edit applies weights immediately but lane_caps rebuilds only at the next flow_step (gen-triggered); draw_bundles sums the stale buffer while the same frame's readout uses fresh qos_pipe_caps — up to one 50ms frame of stripe/readout disagreement after every dial move.",
      "Compute the stripe caps from qos_pipe_caps per bundle member (or rebuild lane_caps eagerly on apply); the comment already documents the readout side of the choice.",
      "confirmed"),
    f(["blind"], "note", "docs-drift",
      "Spec Design Notes list two qos_emphasis.dem captures (~1000ms/~5000ms); the shipped demo records a third (12000ms best-effort-heavy stage)",
      "_bmad-output/implementation-artifacts/spec-3-2-lane-qos.md (Design Notes) vs demos/qos_emphasis.dem:27-29",
      "spec: `- **Demo golden:** `qos_emphasis.dem` captures at ~1000ms (default balanced) and ~5000ms (after `emphasis` + `lane` directives) — the T2 diff IS the \"lane proportions changing\" golden.`; demo: `capture at 1000ms / capture at 5000ms / capture at 12000ms`.",
      "The frozen spec under-describes the golden artifact (the third capture pins the 9000ms best_effort_heavy dial move; the spec's own Suggested Review Order names three stages). Docs drift only — the golden itself is blessed and verified.",
      "Amend the Design Notes to name the third capture (a human-owned spec change).",
      "confirmed"),
    f(["codebase"], "note", "test-helper",
      "check_reject_balance's file assertion is weaker than the sibling check_reject — a wrong-file rejection silently passes",
      "core/catalog_test.odin:209-221 (check_reject_balance) vs :63-80 (check_reject)",
      "check_reject_balance: `if cerr.file != \"balance.json\" { testing.expectf(t, cerr.file != \"\", \"expected a balance.json rejection (rule %q), got %q %q\", want_rule, cerr.file, cerr.rule); return }` — a rejection from another file passes `cerr.file != \"\"` and returns without the rule check. check_reject asserts `cerr.file == want_file` explicitly.",
      "A wrong-file rejection (e.g. the balance fixture accidentally tripping a packet_types rule first) would silently pass all 11 rows. Unreachable today (the four sibling fixtures are fixed-valid), but the helper is the new ODN-5 pin's reader — the inversion is latent.",
      "Mirror check_reject: assert `cerr.file == \"balance.json\"` explicitly before the rule check.",
      "confirmed"),
    f(["codebase"], "note", "cosmetic",
      "OS window title still reads 'v2 story 1.2' while the HUD title was updated to 3.2 in the same diff",
      "app/main.odin:77 (InitWindow) vs app/main.odin:427 (draw_hud title)",
      "app/main.odin:77: `rl.InitWindow(WIN_W, WIN_H, \"Packet Plumber — v2 story 1.2\")`; :427: `draw_text(app, \"Packet Plumber — v2 story 3.2 (3-lane QoS + emphasis dial)\", 12, 10, 22, p.ink)`.",
      "The PR updated the in-HUD banner to 3.2 but left the window title on its stale 'story 1.2' string (stale since 1.4; the diff touched the sibling line). User-visible version inconsistency.",
      "Bump the InitWindow title to the same 3.2 string.",
      "confirmed"),
    f(["edge"], "note", "leak",
      "Demo parse-error paths leak the new emphasis/lanes arrays (early return before the deletes — same as the pre-existing sibling arrays)",
      "harness/demo.odin:128-129; harness/run.odin:130-134, :341-344",
      "harness/demo.odin:128-129: `d.emphasis = make([dynamic]Emphasis_Intent, 0, 4, context.allocator)` / `d.lanes = make([dynamic]Lane_Intent, 0, 4, context.allocator)`; run.odin:130-134: parse-error return before the deferred deletes.",
      "parse_demo allocates the new arrays on context.allocator and any error return drops them (run_demo and load_demo_replay return before the deletes). Small slices on a fatal demo-authoring path; mirrors the pre-existing draws/spawns/demolishes/captures pattern.",
      "Accept as the house pattern, or convert parse_demo to the defer pattern when the loaders are next touched.",
      "confirmed"),
    f(["tests"], "note", "coverage-gap",
      "Node-demolish lane-override purge (apply_demolish_node) has no test — only the pipe-demolish purge is pinned",
      "core/topology.odin:283-287 (apply_demolish_node purge)",
      "core/topology.odin:283-287: `if is_end { t.pipe_alive[pi] = false // incident pipe demolished first (per E1); // 3.2: the incident pipe's lane overrides die with it (same purge as apply_demolish_pipe — deterministic, replay agrees); purge_pipe_overrides(t, t.pipe_id[pi]) }`; qos_test.odin:199-203 pins only Cmd_Demolish_Pipe.",
      "The new purge path in apply_demolish_node is a behavior change in this diff with zero coverage; a regression would serialize dead overrides forever and be silent in every existing test (P3 — the demolish test suite is the neighbor pin).",
      "Extend test_qos_apply_and_resolve (or the demolish suite) with a node-demolish case asserting overrides are purged.",
      "confirmed"),
    f(["tests"], "note", "coverage-gap",
      "lane_presets fail-fast: the 'preset display_name empty' rejection branch has no test row (11 of 12 branches pinned)",
      "core/catalog.odin:490-492; core/catalog_test.odin:186-199",
      "core/catalog.odin:490-492: `if lp.display == \"\" { return {\"balance.json\", lp.id, \"preset display_name empty\"} }`; the bal_rows table (11 rows) covers missing/empty presets, empty id, arity, non-int, negative, over-max, all-zero, unknown default, duplicate id, duplicate weights — no display_name-empty row.",
      "Single unpinned ODN-5 branch in the new loader. P3 — one row away from a complete negative table.",
      "Add the display_name-empty row to bal_rows.",
      "confirmed"),
    f(["tests"], "note", "coverage-gap",
      "lane_presets loader positive path unasserted — parsed values and the absent-default_lane_preset fallback (idx 0) are unpinned",
      "core/catalog.odin:533-535; core/catalog_test.odin:86-105 (BAL_VALID load path)",
      "core/catalog_test.odin:86-105: the positive BAL_VALID load asserts... (BAL_VALID carries lane_presets + default_lane_preset; grep: no assertion reads cat.balance.lane_presets[i].weights or default_preset_idx after a real catalogs_load). All core QoS tests build catalogs via test_catalog (hardcoded presets), bypassing the loader.",
      "A mis-parse of weights or a wrong default index would pass every test (only the harness's data/balance.json load exercises the positive path, and it asserts nothing). The negative table is thorough; the positive mirror is missing.",
      "Assert the parsed presets + default_preset_idx in the existing positive load test.",
      "confirmed"),
    f(["tests"], "note", "coverage-gap",
      "E6 never-drop interactions are pinned only through banking's DEFAULT lane — override-resolved bindings (acceptance AND rejection) are untested",
      "core/qos_test.odin:21-31, :116-120, :138-159",
      "core/qos_test.odin:24-27: `id = \"banking\", display = \"Banking\", ... max_loss_pct = 0, ... default_lane = LANE_EXPRESS`; the E6 tests exercise never-drop only via that default binding (validate_set_emphasis zeroing check + the white-box {0,1,1} force + the override-shaped case at :154-158 parks banking on its OWN default lane).",
      "No test binds a never-drop class to a lane via a Cmd_Set_Lane override (the resolution path qos_lane_of feeds) — neither the acceptance case (override onto a weighted lane succeeds) nor a rejection case (override onto a zeroed non-default lane). The guard/floor agreement claim rests on the default-lane path only.",
      "Add override-resolved E6 tests: never-drop class overridden to a zeroed lane -> rejected; overridden to a weighted lane -> accepted + floored if allocation zeros it.",
      "confirmed"),
    f(["tests"], "note", "coverage-gap",
      "E6 floor is pinned at proc level only — the floored value is never asserted end-to-end through flow_step into lane_caps",
      "core/qos_test.odin:108-115, :195-197",
      "core/qos_test.odin:110-113: `s.topology.pipe_weights[ps] = {0, 1, 1}; caps := qos_pipe_caps(&s.topology, cat, ps, s.topology.pipe_id[ps])` — qos_pipe_caps called DIRECTLY after the force, no step_n after it, so s.flow.lane_caps never carries a floored result; the later lane_caps assertion (:195-197 `testing.expect_value(t, s.flow.lane_caps[0], [3]u32{9, 4, 2})`) is the express_heavy NON-floored path.",
      "The floor contract is pinned at the pure-proc level (test_qos_apply_floor_e6) and qos_pipe_caps is the flow_step callee, but the gen-triggered rebuild that feeds the render + readout never demonstrates a floored lane_caps buffer.",
      "step_n after forcing the weights and assert s.flow.lane_caps carries the floored caps (1,8,7 for cap 15 with E floored).",
      "confirmed"),
]

rejected = [
    {"source": ["blind"], "severity_filed": "warning",
     "title": "lane_presets loader silently skips non-object rows (or_continue)",
     "reason": "Rejected as the established house pattern: every loader since 1.2 uses `lv.(json.Object) or_continue` for array rows (node_types :219, pipe_tiers :255, packet_types, demand — merged + Perkins-verified across 1.2/2.x/3.1 rounds). Round 3.1 rejected the identical finding on the same grounds. The new lane_presets loader mirrors it consistently."},
]

counts = {"blocker": 0, "warning": 0, "note": 0}
for x in findings:
    counts[x["severity"]] += 1

raw_total = 34
merged_unique = len(findings) + len(rejected)

consolidated = {
    "job": "packet-plumber-v2-3.2-lane-qos",
    "round": 1,
    "pr": 31,
    "reviewed_sha": "7c07a80eb6d8274dc6aa49a4e5d7d8dde92bac7c",
    "diff_file": f"{OUT}/diff.patch",
    "chunking": "diff 6912 lines > ~3000 => three file-group chunks, one full 7-lens wave each, sequentially: chunk1 = core (1224 lines, 10 files), chunk2 = app+harness+data+demos+docs (1088 lines, 14 files), chunk3 = goldens (4604 lines, 23 files). Findings merged before verification.",
    "worktree": "/Users/moses/.herdr/worktrees/packet-plumber/perkins-v2-3.2-lane-qos-r1",
    "reviewers_completed": 21,
    "reviewers_total": 21,
    "failed_layers": [],
    "total_findings": raw_total,
    "unique_after_dedupe": merged_unique,
    "verified_confirmed": len(findings),
    "rejected": len(rejected),
    "unverifiable_speculative": 0,
    "counts": counts,
    "verdict": "READY TO MERGE",
    "verdict_reason": "0 blockers. The load-bearing invariants all verified independently at 7c07a80: (1) ODN-11 re-bless PROVEN — splice-proof replayed all 9 old logs with the new code + forced OLD catalog_hash and reproduced every old .t1 bit-for-bit (incl. qos 1500 ticks); all 9 existing demos' T2 pixels pass byte-identical against the unchanged PNGs; every manifest carries the same new catalog_hash c403567796188e5b. (2) E5/E6/E8 contracts pinned + the E6 bus rejection test-bites (neutralizing the guard turns test_qos_bus_rejections_e6 red). (3) Weight-only [ODN-3] respected (no demand input anywhere in lane resolution). (4) Replay determinism [E10]: LOG_VERSION 2 consistent with the 2.3 additive-tag convention; old logs parse under new code, an old binary rejects a new log cleanly; drift-check 69/69 mutations rejected; qos_emphasis replays bit-for-bit. (5) odin test 69/69, harness run 10/10, lint 5/5, app+harness build green at the reviewed sha. All 21 surviving findings are warnings/notes (UI toast gating, app-glue coverage, small validation/leak/docs nits) — nothing blocks merge.",
    "findings": findings,
    "rejected_findings": rejected,
}
with open(f"{OUT}/consolidated.json", "w") as fh:
    json.dump(consolidated, fh, indent=1)
print("consolidated.json written:", counts, "verdict:", consolidated["verdict"])
